### ISSUE TITLE
Identify section of texts which need to be updated for Harvard and propose the needed text

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ui-static#20]
Please comb through the static ui pages at pass.jhu.edu and identify places that are currently JHU specific. These are the places we'll need to swap out/update to make the UI appropriate for Harvard instance. 

Where needed, please propose Harvard specific text to be used on the instance. 

Please record the work of this ticket here https://docs.google.com/document/d/1JAUPKianBeQO-IC82waBPg1mdsU9kTDc0YQth2ptcac/edit

**Comment by jrmartino** [comment]
Some comments on these pages have been recorded in the above document.

**Comment by htpvu** [comment]
thank you @jrmartino

**Comment by htpvu** [comment]
thank you. this was helpful.
