### ISSUE TITLE
Update a FAQ entry 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ui-static#38]
Below is the new text for the question of **"How does PASS collect COVID papers?"**
 

> Submitters from across all JHU divisions can indicate that an author’s accepted manuscript of a journal article is about prior or current COVID-19 related research using a simple checkbox in PASS. This will ensure that the files are deposited in a collection dedicated to that topic: JHU COVID-19 Publications. This provides a dedicated space for this important and comprehensive information related to COVID-19 and follows the guidance of the Johns Hopkins Open Access Policy.

**Comment by jaredgalanis** [comment]
@htpvu are we keeping the contact info?
`If you need help with your submission please contact either Robin Sinn, Sheridan Libraries (rsinn@jhu.edu) or Caitlin Carter, Welch Medical Library (ccarte63@jhmi.edu).`

**Comment by htpvu** [comment]
@jaredgalanis yes please keep those contact info. thank you.
